project:
  type: website
  output-dir: docs

website:
  title: "Mariano Ordano"
  navbar:
    background: "#f8f9fa"
    search: true
    left: []
    right:
      - href: blog.qmd
        text: Bitácora
      - href: proyectos.qmd
        text: Proyectos
      - href: about.qmd
        text: Acerca de

  page-footer: 
    left: "2026 Mariano Ordano | Versión 1.0 Quarto"
    right: 
      - icon: github
        href: https://github.com/maordano/
        aria-label: GitHub
      - icon: linkedin
        href: https://linkedin.com  # Reemplazá con tu enlace
        aria-label: LinkedIn
      - text: "OSF"
        href: https://osf.io/9yxfm/
      - text: "ResearchGate"  # Al no haber icono nativo directo, el texto limpio funciona muy bien
        href: https://researchgate.net
      - icon: instagram
        href: https://instagram.com/mariano.ordano/
        aria-label: Instagram
      - text: "cv"  # botón directo al CV
        href: https://drive.google.com/file/d/1fwCgR2HiVTTu7CEI3Vsi1gWZcUNglawJ/view
        
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: 
      text: |
        <script type="text/javascript">
          function googleTranslateElementInit() {
            new google.translate.TranslateElement({pageLanguage: 'es', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
          }
        </script>
        <script type="text/javascript" src="//://google.com"></script>
    include-after-body: 
      text: |
        <div id="google_translate_element" style="position: fixed; bottom: 20px; left: 20px; z-index: 1000; background: #fff; padding: 5px; border-radius: 4px; box-shadow: 0 2px 5px rgba(0,0,0,0.15);"></div>

execute:
  freeze: true
