baseURL = "https://maordano.github.io/"
languageCode = "es-ar"
title = "Mariano Ordano"
theme = "ananke"
publishDir = "docs"
enableRobotsTXT = true

[outputs]
  home = ["HTML", "RSS", "JSON", "sitemap", "robots"]
  section = ["HTML", "RSS", "JSON","sitemap"]
  page = ["HTML","sitemap"]

[outputFormats.sitemap]
  mediatype = "application/xml"
  baseName = "sitemap"
  isPlainText = true
  isHTML = false

[outputFormats.robots]
  mediatype = "text/plain"
  baseName = "robots"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Investigador en ecología y evolución de interacciones bióticas | Fundación Miguel Lillo · IER-CONICET"
  featured_image = "/images/alba-bird-tree-4594.webp"
  body_classes = "avenir bg-washed-blue"
  version = "0.2.0"
  featured_image_class = "cover bg-center"
  enableRobotsTXT = true
[[params.oss_projects]]

[params.ananke]
  show_recent_posts = false

[params.ananke.social]
[params.ananke.social.follow]
 networks = ["linkedin", "github","osf","researchgate","instagram"]

[params.ananke.social.linkedin]
  username = "mariano-ordano"

[params.ananke.social.networks.linkedin]
  profile = "https://www.linkedin.com/in/mariano-ordano"

[params.ananke.social.github]
  username = "maordano"

[params.ananke.social.networks.researchgate]
  slug = "researchgate"
  label = "ResearchGate"
  color = "#00CCBB"
  profile = "https://www.researchgate.net/profile/%s"
  icon = "researchgate"

[params.ananke.social.researchgate]
  username = "Mariano-Ordano"
  
[params.ananke.social.instagram]
  username = "mariano.ordano"

[params.ananke.social.networks.osf]
  slug = "osf"
  label = "OSF"
  color = "#4eb1ba"
  profile = "https://osf.io/%s"
  icon = "osf"

[params.ananke.social.osf]
  username = "9yxfm"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[menu]
  [[menu.main]]
    name = "Bitácora"
    url = "/post/"
    weight = 1
