baseURL = "https://maordano.github.io/"
languageCode = "es-ar"
title = "Mariano Ordano"
theme = "ananke"
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Investigador | Fundación Miguel Lillo · IER-CONICET"
  featured_image = "/images/riparium-cielo.png"
  body_classes = "avenir bg-washed-blue"
  version = "0.1.0"

[[params.oss_projects]]


[params.ananke]
  show_recent_posts = false

[params.ananke.social]
[params.ananke.social.follow]
 networks = ["linkedin", "github", "researchgate", "instagram"]

[params.ananke.social.linkedin]
  username = "mariano-ordano"

[params.ananke.social.github]
  username = "maordano"

[params.ananke.social.networks.researchgate]
  slug = "researchgate"


  label = "ResearchGate"
  color = "#00CCBB"
  profile = "https://www.researchgate.net/profile/%s"
  icon = "researchgate"

[params.ananke.social.researchgate]
  username = "Mariano-Ordano"
  
[params.ananke.social.instagram]
  username = "mariano.ordano"


[menu]
  [[menu.main]]
    name = "Bitácora"
    url = "/post/"
    weight = 1

    